name: God Hates Christians
favicon: null
layout_spectrum: 0.6708053771872073
typography_spectrum: 0.5362691464833915
title: God Hates Christians
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71756403-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.1725087841041386
  lightness: 0.25318753346800804
  saturation: 0.2934663768392056
  rhythmicContrast: 0.4109192471951246
purpose: []
