name: God Hates Christians
favicon: null
layout_spectrum: 0.74457
typography_spectrum: 0.98832
title: God Hates Christians - The plight of Christians around the world
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71756403-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfccae'
    - '#221e13'
    - '#6c4534'
    - '#c58049'
    - '#858c60'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
